title: Porteføljestyring af OS2-projekter og -produkter
description: Indeholder dokumentation i relation til OS2s porteføljestyring og arbejde med OS2s styringsmodel.
theme: just-the-docs
logo: "/assets/images/os2_logo.png"
color_scheme: wider
back_to_top: true
back_to_top_text: "Til toppen"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.9.0"

aux_links:
  Repository: https://github.com/OS2offdig/os2-product-audits
#  Maintainers: ./MAINTAINERS
#  Contribute: ./CONTRIBUTING